/*login*/
insert into login (user_name, password, enabled, role) values('admin', 'secret', true, 'ROLE_ADMIN');

/*products*/
insert into products(name, description, image) values('Cash and Valuables in Transit', 'All risk cover for your cash and valuables whilst in transit.', '/img/products/Cash and Valuables in Transit.jpg');
insert into products(name, description, image) values('Static Cover Cash and Valuables', 'All risk cover for your cash and valuables whilst static/on-site in vault or safe.','/img/products/Static Cover Cash and Valuables1.jpg');
insert into products(name, description, image) values('Fine Art and Collectables', 'Tailored cover for your treasured possessions.', '/img/products/Fine Art and Collectables.jpg');
insert into products(name, description, image) values('Static and In Transit Cover Cash and Valuables', 'All risk cover for cash/valuables whilst in transit and static/on-site in vault or safe.', '/img/products/Static and In Transit Cover Cash and Valuables1.jpeg');


/*broker*/
insert into brokers(code, name, email) values ('00001', 'Coin Risk Management', 'binod.sethi@reverside.co.za');
insert into brokers(code, name, email) values ('00002', 'Admin Focus (Pty) Ltd', 'thabo.thulare@reverside.co.za');
insert into brokers(code, name, email) values ('00003', 'Optimum Financial Services Group', 'lesetja.konaite@reverside.co.za');
insert into brokers(code, name, email) values ('00004', 'Status Insurance Brokers (Pty) Ltd', 'info@statusib.co.za');
insert into brokers(code, name, email) values ('00005', 'Van Zyl Conradie Makelaars', 'elana@vzcon.co.za');
insert into brokers(code, name, email) values ('00006', 'Safari & Tourism Insurance Brokers (Pty) Ltd', 'yvonne@satib.co.za');
insert into brokers(code, name, email) values ('00007', 'Rens Kontant in Transito', 'renscit@vodamail.co.za');
insert into brokers(code, name, email) values ('00008', 'Multi Risk Admin (Pty) Ltd', 'queries@multirisk.co.za');
insert into brokers(code, name, email) values ('00009', 'Lazarus Dash and Associates (Pty) Ltd', 'Brian@lazdash.co.za');
insert into brokers(code, name, email) values ('00010', 'Willem Jacobus Nienaber', 'wjnienaber@telkomsa.net');
insert into brokers(code, name, email) values ('00011', 'Deposita Systems (Pty) Ltd', 'lizaan.botha@reverside.co.za');


/*answer_type*/
insert into answer_types(answer_type) values('text');
insert into answer_types(answer_type) values('number');
insert into answer_types(answer_type) values('select');
insert into answer_types(answer_type) values('checkbox');
insert into answer_types(answer_type) values('textarea');
insert into answer_types(answer_type) values('date');
insert into answer_types(answer_type) values('other');


/*Product1*/
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '1', 'What do you wish to insure ?',                 3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Fine Art');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Bullion');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Precious Stones');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Other');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '2', 'Please specify what you wish to insure ?',                 7,  1,    'Other', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '3', 'What is the maximum amount you wish to insure ?',                      2, 	null, 	null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '4', 'Is the above amount the total full value of the goods being moved ?',  4,	null, 	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '5', 'What is the total full value of the goods being moved ?',              2,   4, 		'false', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '6', 'Do you want first loss cover for additional premium ?',               4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '7', 'Do you use the service of a professional valuables carriers ?',        4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '8', 'What is the name of the professional valuables carriers ?',            3,   7,	  	'true', 'true');
insert into answer_values(questionnaire_id, answer_value) values(8, 'Protea Coin Service');
insert into answer_values(questionnaire_id, answer_value) values(8, 'G4S Service');
insert into answer_values(questionnaire_id, answer_value) values(8, 'Fidelity Service');
insert into answer_values(questionnaire_id, answer_value) values(8, 'Imeprial Logistics');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '9', 'Please specify by whom and how are the valuables carried :',                           1,	7, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '10', 'How many times per week are the valuables carried ?',                   3,  null,  	null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(10, '1 time /week');
insert into answer_values(questionnaire_id, answer_value) values(10, '2 times/week');
insert into answer_values(questionnaire_id, answer_value) values(10, '3 times/week');
insert into answer_values(questionnaire_id, answer_value) values(10, '4 times/week');
insert into answer_values(questionnaire_id, answer_value) values(10, '5 times/week');
insert into answer_values(questionnaire_id, answer_value) values(10, '6 times/week');
insert into answer_values(questionnaire_id, answer_value) values(10, '7 times/week');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '11', 'Please provide from where the valuables carried ?',                    1,    null,  null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '12', 'Please provide to where are the valuables carried ?',                    1,    null,  null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '13', 'What is the approximate distance ?'                 ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(13, '0km to 100km');
insert into answer_values(questionnaire_id, answer_value) values(13, '100km to 200km');
insert into answer_values(questionnaire_id, answer_value) values(13, '200km to 300km');
insert into answer_values(questionnaire_id, answer_value) values(13, '300km to 400km');
insert into answer_values(questionnaire_id, answer_value) values(13, '400km to 500km');
insert into answer_values(questionnaire_id, answer_value) values(13, '500km to 600km');
insert into answer_values(questionnaire_id, answer_value) values(13, '600km to 700km');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '14', 'Please select the duration for your cover  ?'                     ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(14, 'Annually');
insert into answer_values(questionnaire_id, answer_value) values(14, 'Monthly');
insert into answer_values(questionnaire_id, answer_value) values(14, 'Once-Off');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '15', 'Please specify policy insecption date for annual cover :'                     ,                    6,    14,  'Annually', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '16', 'Please specify policy insecption date for monthly cover :'                     ,                    6,    14,  'Monthly', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '17', 'Please specify from date for once-off:'                     ,                    6,    14,  'Once-Off', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '18', 'Please specify end date for once-off :'                     ,                    6,    14,  'Once-Off', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '19', 'Are you currently insured ?'                     ,                      4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '20', 'Please provide details of your previous insurance company :',           1,    19,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '21', 'Please provide details of losses of valuable goods of insured/uninsured the past 5 years ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '22', 'DATE :'                     ,                    6,    21,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '23', 'VALUE :'                     ,                    2,    21,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '24', 'TYPE OF LOSS :'                     ,                    1,    21,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '25', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    21,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '26', 'DATE :'                     ,                    6,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '27', 'VALUE :'                     ,                    2,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '28', 'TYPE OF LOSS :'                     ,                    1,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '29', 'Do you have more history details of insured/uninsured goods :'                    ,                    4,    25,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '30', 'DATE :'                     ,                    6,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '31', 'VALUE :'                     ,                    2,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '32', 'TYPE OF LOSS :'                     ,                    1,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '33', 'Do you have more history details of insured/uninsured goods :'                    ,                    4,    29,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '34', 'DATE :'                     ,                    6,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '35', 'VALUE :'                     ,                    2,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '36', 'TYPE OF LOSS :'                     ,                    1,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '37', 'Do you require SASRIA cover ?'                     ,                    4,    null,  null, 'false');




/*Product2*/
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '38', 'What do you wish to insure ?',                 3,  null,    null, true);
insert into answer_values(questionnaire_id, answer_value) values(38, 'Cash');
insert into answer_values(questionnaire_id, answer_value) values(38, 'Fine Art');
insert into answer_values(questionnaire_id, answer_value) values(38, 'Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(38, 'Bullion');
insert into answer_values(questionnaire_id, answer_value) values(38, 'Precious Stones');
insert into answer_values(questionnaire_id, answer_value) values(38, 'Other');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '39', 'Please specify what you wish to insure ?',                 7,  1,    'Other', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '40', 'What is the maximum amount you wish to insure ?', 				    2, 	null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '41', 'Is the above amount the total full value of the goods being stored ?',  4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '42', 'What is the total full value of the goods being stored ?',             2,  4,  'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '43', 'Please give a full description of the goods to be insured :',          1,  null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '44', 'Please provide details of vault/safe :',                                      4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '45', 'Are the goods going to be stored in vault ?',                                       4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '46', 'Is the vault secured with reinforced concrete on all sides as well as top and bottom ?',                 4,  8,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '47', 'Is vault fitted with interior seismic detectors inside the vault ?',                 4,  8,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '48', 'Is vault equipped with 24 hour infra-red cameras and normal CCTV 24 hours recording ?',                 4,  8,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '49', 'Does the vault have an alarm and is it linked to an external response company ?',                 4,  8,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '50', 'What is the type of storage of vault ?',                1,  8,    'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '51', 'What is the address of the stored vault ?',                 1,  8,    'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '52', 'Please select the SABS safety category of the vault :',              3,  null,   null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(52, 'No SABS grading');
insert into answer_values(questionnaire_id, answer_value) values(52, 'SABS Category I ');
insert into answer_values(questionnaire_id, answer_value) values(52, 'SABS Category II');
insert into answer_values(questionnaire_id, answer_value) values(52, 'SABS Category II HD grading');
insert into answer_values(questionnaire_id, answer_value) values(52, 'SABS Category II ADM');
insert into answer_values(questionnaire_id, answer_value) values(52, 'SABS Category II ADM Grading D3');
insert into answer_values(questionnaire_id, answer_value) values(52, 'SABS Category III grading');
insert into answer_values(questionnaire_id, answer_value) values(52, 'SABS Category IV grading');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '53', 'Please select the duration for your cover  ?'                     ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(53, 'Annually');
insert into answer_values(questionnaire_id, answer_value) values(53, 'Monthly');
insert into answer_values(questionnaire_id, answer_value) values(53, 'Once-Off');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '54', 'Please specify policy insecption date for annual cover :'                     ,                    6,    16,  'Annually', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '55', 'Please specify policy insecption date for monthly cover :'                     ,                    6,    16,  'Monthly', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '56', 'Please specify from date for once-off:'                     ,                    6,    16,  'Once-Off', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '57', 'Please specify end date for once-off :'                     ,                    6,    16,  'Once-Off', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '58', 'Please specify if secured by any other means :',                 4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '59', 'Please provide details of how it is secured :',                 1,    21,    'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '60', 'Are you currently insured ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '61', 'Please provide details of your previous insurance company ?'                     ,                    1,    23,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '62', 'Please provide details of losses of valuable goods of insured/uninsured the past 5 years ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '63', 'DATE :'                    ,                    6,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '64', 'VALUE :'                     ,                    2,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '65', 'TYPE OF LOSS :'                     ,                    1,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '66', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    25,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '67', 'DATE :'                     ,                    6,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '68', 'VALUE :'                     ,                    2,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '69', 'TYPE OF LOSS :'                     ,                    1,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '70', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    29,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '71', 'DATE :'                     ,                    6,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '72', 'VALUE :'                     ,                    2,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '73', 'TYPE OF LOSS :'                     ,                    1,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '74', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    33,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '75', 'DATE :'                     ,                    6,    37,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '76', 'VALUE :'                     ,                    2,    37,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '77', 'TYPE OF LOSS :'                     ,                    1,    37,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '78', 'Do you require SASRIA cover ?',                 4,  null,    null, 'false');


/*Product3*/
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '79', 'What do you wish to insure ?',                 3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(79, 'Cash');
insert into answer_values(questionnaire_id, answer_value) values(79, 'Fine Art');
insert into answer_values(questionnaire_id, answer_value) values(79, 'Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(79, 'Bullion');
insert into answer_values(questionnaire_id, answer_value) values(79, 'Precious Stones');
insert into answer_values(questionnaire_id, answer_value) values(79, 'Other');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '80', 'Please specify what you wish to insure ?',                 7,  1,    'Other', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '81', 'Please select the duration for your cover  ?'                     ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(81, 'Annually');
insert into answer_values(questionnaire_id, answer_value) values(81, 'Monthly');
insert into answer_values(questionnaire_id, answer_value) values(81, 'Once-Off');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '82', 'Please specify policy insecption date for annual cover :'                     ,                    6,    3,  'Annually', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '83', 'Please specify policy insecption date for monthly cover :'                     ,                    6,    3,  'Monthly', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '84', 'Please specify from date for once-off:'                     ,                    6,    3,  'Once-Off', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '85', 'Please specify end date for once-off :'                     ,                    6,    3,  'Once-Off', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '86', 'What is the maximum amount you wish to insure ?',                      2, 	null, 	null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '87', 'Is the above amount the total full value of the goods being moved ?',  4,	null, 	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '88', 'What is the total full value of the goods being moved ?',              2,   9, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '89', 'Do you want first loss cover for additional premium ?',               4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '90', 'Do you use the service of a professional valuables carriers ?',        4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '91', 'What is the name of the professional valuables carriers ?',            3,   12,	  	'true', 'true');
insert into answer_values(questionnaire_id, answer_value) values(91, 'Protea Coin Service');
insert into answer_values(questionnaire_id, answer_value) values(91, 'G4S Service');
insert into answer_values(questionnaire_id, answer_value) values(91, 'Fidelity Service');
insert into answer_values(questionnaire_id, answer_value) values(91, 'Imperial Logistics');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '92', 'Please specify by whom and how are the valuables carried :',                           1,	12, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '93', 'How many times per week are the valuables carried ?',                   3,  null,  	null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(93, '1 time /week');
insert into answer_values(questionnaire_id, answer_value) values(93, '2 times/week');
insert into answer_values(questionnaire_id, answer_value) values(93, '3 times/week');
insert into answer_values(questionnaire_id, answer_value) values(93, '4 times/week');
insert into answer_values(questionnaire_id, answer_value) values(93, '5 times/week');
insert into answer_values(questionnaire_id, answer_value) values(93, '6 times/week');
insert into answer_values(questionnaire_id, answer_value) values(93, '7 times/week');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '94', 'Please provide from where the valuables carried ?',                    1,    null,  null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '95', 'Please provide to where are the valuables carried ?',                    1,    null,  null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '96', 'What is the approximate distance ?'                 ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(96, '0km to 100km');
insert into answer_values(questionnaire_id, answer_value) values(96, '100km to 200km');
insert into answer_values(questionnaire_id, answer_value) values(96, '200km to 300km');
insert into answer_values(questionnaire_id, answer_value) values(96, '300km to 400km');
insert into answer_values(questionnaire_id, answer_value) values(96, '400km to 500km');
insert into answer_values(questionnaire_id, answer_value) values(96, '500km to 600km');
insert into answer_values(questionnaire_id, answer_value) values(96, '600km to 700km');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '97', 'Are you currently insured ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '98', 'Please provide details of your previous insurance company :'                     ,                    1,   19,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '99', 'Please provide details of losses of valuable goods of insured/uninsured the past 5 years ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '100', 'DATE :'                    ,                    6,    21,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '101', 'VALUE :'                     ,                    2,    21,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '102', 'TYPE OF LOSS :'                     ,                    1,    21,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '103', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    21,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '104', 'DATE :'                     ,                    6,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '105', 'VALUE :'                     ,                    2,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '106', 'TYPE OF LOSS :'                     ,                    1,    25,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '107', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    25,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '108', 'DATE :'                     ,                    6,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '109', 'VALUE :'                     ,                    2,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '110', 'TYPE OF LOSS :'                     ,                    1,    29,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '111', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    29,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '112', 'DATE :'                     ,                    6,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '113', 'VALUE :'                     ,                    2,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '114', 'TYPE OF LOSS :'                     ,                    1,    33,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '115', 'Do you require SASRIA cover ?'                     ,                    4,    null,  null, 'false');


/*product4*/
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '116', 'What do you wish to insure ?',                 3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(116, 'Cash');
insert into answer_values(questionnaire_id, answer_value) values(116, 'Fine Art');
insert into answer_values(questionnaire_id, answer_value) values(116, 'Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(116, 'Bullion');
insert into answer_values(questionnaire_id, answer_value) values(116, 'Precious Stones');
insert into answer_values(questionnaire_id, answer_value) values(116, 'Other');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '117', 'Please specify what you wish to insure ?',                 7,  1,    'Other', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '118', 'What is the maximum amount you wish to insure in Cash in transit ?',                      2, 	null, 	null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '119', 'Is the above amount the total full value of the goods being moved in  Cash in transit ?',  4,	null, 	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '120', 'What is the total full value of the goods being moved in Cash in transit ?',              2,   4, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '121', 'Do you want first loss cover for additional premium ?',               4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '122', 'Do you use the service of a professional valuables carriers ?',        4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '123', 'What is the name of the professional valuables carriers ?',            3,   7,	  	'true', 'true');
insert into answer_values(questionnaire_id, answer_value) values(123, 'Protea Coin Service');
insert into answer_values(questionnaire_id, answer_value) values(123, 'G4S Service');
insert into answer_values(questionnaire_id, answer_value) values(123, 'Fidelity Service');
insert into answer_values(questionnaire_id, answer_value) values(123, 'Imperial Logistics');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '124', 'Please specify by whom and how are the valuables carried :',                           1,	7, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '125', 'Please select the duration for your cover  ?'                     ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(125, 'Annually');
insert into answer_values(questionnaire_id, answer_value) values(125, 'Monthly');
insert into answer_values(questionnaire_id, answer_value) values(125, 'Once-Off');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '126', 'Please specify policy insecption date for annual cover :'                     ,                    6,    10,  'Annually', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '127', 'Please specify policy insecption date for monthly cover :'                     ,                    6,    10,  'Monthly', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '128', 'Please specify from date for once-off:'                     ,                    6,    10,  'Once-Off', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '129', 'Please specify end date for once-off :'                     ,                    6,    10,  'Once-Off', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '130', 'How many times per week are the valuables carried ?',                   3,  null,  	null, true);
insert into answer_values(questionnaire_id, answer_value) values(130, '1 time /week');
insert into answer_values(questionnaire_id, answer_value) values(130, '2 times/week');
insert into answer_values(questionnaire_id, answer_value) values(130, '3 times/week');
insert into answer_values(questionnaire_id, answer_value) values(130, '4 times/week');
insert into answer_values(questionnaire_id, answer_value) values(130, '5 times/week');
insert into answer_values(questionnaire_id, answer_value) values(130, '6 times/week');
insert into answer_values(questionnaire_id, answer_value) values(130, '7 times/week');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '131', 'Please provide from where the valuables carried ?',                    1,    null,  null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '132', 'Please provide to where are the valuables carried ?',                    1,    null,  null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '133', 'What is the approximate distance ?'                 ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(133, '0km to 100km');
insert into answer_values(questionnaire_id, answer_value) values(133, '100km to 200km');
insert into answer_values(questionnaire_id, answer_value) values(133, '200km to 300km');
insert into answer_values(questionnaire_id, answer_value) values(133, '300km to 400km');
insert into answer_values(questionnaire_id, answer_value) values(133, '400km to 500km');
insert into answer_values(questionnaire_id, answer_value) values(133, '500km to 600km');
insert into answer_values(questionnaire_id, answer_value) values(133, '600km to 700km');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '134', 'What is the maximum amount you wish to insure in Static ?', 				    2, 	null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '135', 'Is the above amount the total full value of the goods being stored in Static ?',  4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '136', 'What is the total full value of the goods being stored in Static ?',             2,  20,  false, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '137', 'Please give a full description of the goods to be insured ?',          1,  null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '138', 'Please provide details of vault/safe ?',                                      4,  null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '139', 'Please select the SABS safety category of the vault:',              3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(139, 'No SABS grading');
insert into answer_values(questionnaire_id, answer_value) values(139, 'SABS Category I ');
insert into answer_values(questionnaire_id, answer_value) values(139, 'SABS Category II');
insert into answer_values(questionnaire_id, answer_value) values(139, 'SABS Category II HD grading');
insert into answer_values(questionnaire_id, answer_value) values(139, 'SABS Category II ADM');
insert into answer_values(questionnaire_id, answer_value) values(139, 'SABS Category II ADM Grading D3');
insert into answer_values(questionnaire_id, answer_value) values(139, 'SABS Category III grading');
insert into answer_values(questionnaire_id, answer_value) values(139, 'SABS Category IV grading');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '140', 'Are the goods going to be stored in vault ?',                                       4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '141', 'Is the vault secured with reinforced concrete on all sides as well as top and bottom ?',                 4,  25,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '142', 'Is vault fitted with interior seismic detectors inside the vault ?',                 4,  25,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '143', 'Is vault equipped with 24 hour infra-red cameras and normal CCTV 24 hours recording ?',                 4,  25,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '144', 'Does the vault have an alarm and is it linked to an external response company ?',                 4,  25,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '145', 'What is the type of storage of vault ?',                 1,  25,    'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '146', 'What is the address of the stored vault?',                 1,  25,    'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '147', 'Please specify if secured by any other means :',                 4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '148', 'Please provide details of how it is secured :',                 1,    32,    'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '149', 'Are you currently insured ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '150', 'Please provide details of your previous insurance company :'                     ,                    1,    34,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '151', 'Please provide details of losses of valuable goods of insured/uninsured the past 5 years ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '152', 'DATE :'                     ,                    6,    36,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '153', 'VALUE :'                     ,                    2,    36,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '154', 'TYPE OF LOSS :'                     ,                    1,    36,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '155', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    36,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '156', 'DATE :'                     ,                    6,    40,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '157', 'VALUE :'                     ,                    2,    40,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '158', 'TYPE OF LOSS :'                     ,                    1,    40,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '159', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    40,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '160', 'DATE :'                     ,                    6,    44,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '161', 'VALUE :'                     ,                    2,    44,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '162', 'TYPE OF LOSS :'                     ,                    1,    44,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '163', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    44,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '164', 'DATE :'                     ,                    6,    48,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '165', 'VALUE :'                     ,                    2,    48,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '166', 'TYPE OF LOSS :'                     ,                    1,    48,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '167', 'Do you require SASRIA cover ?',                 4,  null,    null, 'false');



insert into bank_accounts(account_number, account_name, branch, bank_name)values('236777262','Thabo','5678','Standard Bank');
insert into bank_accounts(account_number, account_name, branch, bank_name)values('3425672872','Lenox','6756','Nedbank');
insert into bank_accounts(account_number, account_name, branch, bank_name)values('2345656','Binod','7889','Standard Bank');


insert into contacts(street, code, suburb, work_tel_number, fax_number, email, contact_person) values('umtholo','8909','Birch Acres','011 991 0000','086 575 7876','thabo@gmail.com','Thabo Thulare');
insert into contacts(street, code, suburb, work_tel_number, fax_number, email, contact_person) values('old road','6765','Oliven','015 787 9788','086 671 7887','Lenox@reverside.co.za','Lenox');
insert into contacts(street, code, suburb, work_tel_number, fax_number, email, contact_person) values('zurich','9866','Sandton','012 876 7876','012 655 8987','binod@gmail.com','Binod Sethi');

insert into clients(bank_account_id, contact_id, company_name,reg_no, income_tax_number, vat_number) values('1','1','Reverside','5TTDDFU78','234599','TRUI5555');
insert into clients(bank_account_id, contact_id, company_name,reg_no, income_tax_number, vat_number) values('2','2','Zurich','567RRFCD','2345678','TRE123456');
insert into clients(bank_account_id, contact_id, company_name,reg_no, income_tax_number, vat_number) values('3','3','Reverside Software Solutions','5TTDDFU78','234599','TRUI5555');