insert into login (user_name, password, enabled, role) values('admin', 'secret', true, 'ROLE_ADMIN');

insert into products(name, description, image) values('Cash and Valuables in Transit', 'All risk cover for your cash and valuables whilst in transit.', '/img/products/Cash and Valuables in Transit.jpg');
insert into products(name, description, image) values('Static Cover Cash and Valuables', 'All risk cover for your cash and valuables whilst static/on-site in vault or safe.','/img/products/Static Cover Cash and Valuables1.jpg');
insert into products(name, description, image) values('Fine Art and Collectables', 'Tailored cover for your treasured possessions.', '/img/products/Fine Art and Collectables.jpg');
insert into products(name, description, image) values('Static and In Transit Cover Cash and Valuables', 'All risk cover for cash/valuables whilst in transit and static/on-site in vault or safe.', '/img/products/Static and In Transit Cover Cash and Valuables1.jpeg');


/*broker*/
insert into brokers(code, name, email) values ('00001', 'Coin Risk Management', 'binod.sethi@reverside.co.za');
insert into brokers(code, name, email) values ('00002', 'Admin Focus (Pty) Ltd', 'thabo.thulare@reverside.co.za');
insert into brokers(code, name, email) values ('00003', 'Optimum Financial Services Group', 'lesetja.konaite@reverside.co.za');
insert into brokers(code, name, email) values ('00004', 'Status Insurance Brokers (Pty) Ltd', 'info@statusib.co.za');
insert into brokers(code, name, email) values ('00005', 'Van Zyl Conradie Makelaars', 'elana@vzcon.co.za');
insert into brokers(code, name, email) values ('00006', 'Safari & Tourism Insurance Brokers (Pty) Ltd', 'yvonne@satib.co.za');
insert into brokers(code, name, email) values ('00007', 'Rens Kontant in Transito', 'renscit@vodamail.co.za');
insert into brokers(code, name, email) values ('00008', 'Multi Risk Admin (Pty) Ltd', 'queries@multirisk.co.za');
insert into brokers(code, name, email) values ('00009', 'Lazarus Dash and Associates (Pty) Ltd', 'Brian@lazdash.co.za');
insert into brokers(code, name, email) values ('00010', 'Willem Jacobus Nienaber', 'wjnienaber@telkomsa.net');
insert into brokers(code, name, email) values ('00011', 'Deposita Systems (Pty) Ltd', 'lizaan.botha@reverside.co.za');


/*answer_type*/
insert into answer_types(answer_type) values('text');
insert into answer_types(answer_type) values('number');
insert into answer_types(answer_type) values('select');
insert into answer_types(answer_type) values('checkbox');
insert into answer_types(answer_type) values('textarea');

/*Product1*/
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '1', 'What do you wish to insure ?',                 3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash and Coins ');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash Coins and Valuables');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash Belonging to Standard Bank');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash Gold And Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash and Cameos Managed Units');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash and Gold Bullion');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash and Bullion');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Cash and Valuables');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Gold and Cash');
insert into answer_values(questionnaire_id, answer_value) values(1, 'Bullion');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '2', 'What is the maximum amount you wish to insure ?',                      2, 	null, 	null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '3', 'Is the above amount the total full value of the goods being moved ?',  4,	null, 	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '4', 'What is the total full value of the goods being moved ?',              2,   3, 		'false', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '5', 'Do you want first loss cover for additional premium ?',               4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '6', 'Do you use the service of a professional valuables carriers ?',        4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '7', 'What is the name of the professional valuables carriers ?',            3,   6,	  	'true', 'true');
insert into answer_values(questionnaire_id, answer_value) values(7, 'Protea Coin Service');
insert into answer_values(questionnaire_id, answer_value) values(7, 'G4S Service');
insert into answer_values(questionnaire_id, answer_value) values(7, 'Fidelity Service');
insert into answer_values(questionnaire_id, answer_value) values(7, 'Imeprial Logistics');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '8', 'Please specify by whom and how are the valuables carried :',                           1,	6, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '9', 'How many times per week are the valuables carried ?',                   3,  null,  	null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(9, '1 time /week');
insert into answer_values(questionnaire_id, answer_value) values(9, '2 times/week');
insert into answer_values(questionnaire_id, answer_value) values(9, '3 times/week');
insert into answer_values(questionnaire_id, answer_value) values(9, '4 times/week');
insert into answer_values(questionnaire_id, answer_value) values(9, '5 times/week');
insert into answer_values(questionnaire_id, answer_value) values(9, '6 times/week');
insert into answer_values(questionnaire_id, answer_value) values(9, '7 times/week');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '10', 'Please select from where and to where are the valuables carried :',                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(10, 'Port Elizabeth to Bloemfontein');
insert into answer_values(questionnaire_id, answer_value) values(10, 'Johannesburg to Durban');
insert into answer_values(questionnaire_id, answer_value) values(10, 'Polokwane to Mbombela');
insert into answer_values(questionnaire_id, answer_value) values(10, 'Rustenburg to Kimberley');
insert into answer_values(questionnaire_id, answer_value) values(10, 'Kimberley to Cape Town');
insert into answer_values(questionnaire_id, answer_value) values(10, 'Cape Town to Johannesburg ');
insert into answer_values(questionnaire_id, answer_value) values(10, 'Durban to Bloemfontein');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '11', 'What is the approximate distance ?'                 ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(11, '0km to 100km');
insert into answer_values(questionnaire_id, answer_value) values(11, '100km to 200km');
insert into answer_values(questionnaire_id, answer_value) values(11, '200km to 300km');
insert into answer_values(questionnaire_id, answer_value) values(11, '300km to 400km');
insert into answer_values(questionnaire_id, answer_value) values(11, '400km to 500km');
insert into answer_values(questionnaire_id, answer_value) values(11, '500km to 600km');
insert into answer_values(questionnaire_id, answer_value) values(11, '600km to 700km');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '12', 'Please select the durtaion for your cover  ?'                     ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(12, 'Annually');
insert into answer_values(questionnaire_id, answer_value) values(12, 'Monthly');
insert into answer_values(questionnaire_id, answer_value) values(12, 'Once Off');
insert into answer_values(questionnaire_id, answer_value) values(12, 'Permanent');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '13', 'Are you currently insured ?'                     ,                      4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '14', 'Please provide details of your previous insurance company :',           1,    13,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '15', 'Please provide details of losses of valuable goods of insured/uninsured the past 5 years ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '16', 'DATE :'                     ,                    1,    15,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '17', 'VALUE :'                     ,                    1,    15,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '18', 'TYPE OF LOSS :'                     ,                    1,    15,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '19', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    15,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '20', 'DATE :'                     ,                    1,    19,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '21', 'VALUE :'                     ,                    1,    19,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '22', 'TYPE OF LOSS :'                     ,                    1,    19,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '23', 'Do you have more history details of insured/uninsured goods :'                    ,                    4,    19,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '24', 'DATE :'                     ,                    1,    23,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '25', 'VALUE :'                     ,                    1,    23,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '26', 'TYPE OF LOSS :'                     ,                    1,    23,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '27', 'Do you have more history details of insured/uninsured goods :'                    ,                    4,    23,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '28', 'DATE :'                     ,                    1,    27,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '29', 'VALUE :'                     ,                    1,    27,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '30', 'TYPE OF LOSS :'                     ,                    1,    27,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('1', '31', 'Do you require SASRIA cover ?'                     ,                    4,    null,  null, 'false');




/*Product2*/
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '32', 'What do you wish to insure ?',                 3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash and Coins ');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash Coins and Valuables');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash Belonging to Standard Bank');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash Gold And Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash and Cameos Managed Units');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash and Gold Bullion');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash and Bullion');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Cash and Valuables');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Gold and Cash');
insert into answer_values(questionnaire_id, answer_value) values(32, 'Bullion');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '33', 'What is the maximum amount you wish to insure ?', 				    2, 	null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '34', 'Is the above amount the total full value of the goods being stored ?',  4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '35', 'What is the total full value of the goods being stored ?',             2,  3,  'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '36', 'Please give a full description of the goods to be insured :',          1,  null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '37', 'Please provide details of vault/safe :',                                      4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '38', 'Are the goods going to be stored in vault ?',                                       4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '39', 'Is the vault secured with reinforced concrete on all sides as well as top and bottom ?',                 4,  7,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '40', 'Is vault fitted with interior seismic detectors inside the vault ?',                 4,  7,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '41', 'Is vault equipped with 24 hour infra-red cameras and normal CCTV 24 hours recording ?',                 4,  7,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '42', 'Does the vault have an alarm and is it linked to an external response company ?',                 4,  7,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '43', 'What is the type of storage of vault ?',                1,  7,    'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '44', 'What is the address of the stored vault ?',                 1,  7,    'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '45', 'Please select the SABS safety category of the vault :',              3,  null,   null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(45, 'No SABS grading');
insert into answer_values(questionnaire_id, answer_value) values(45, 'SABS Category I ');
insert into answer_values(questionnaire_id, answer_value) values(45, 'SABS Category II');
insert into answer_values(questionnaire_id, answer_value) values(45, 'SABS Category II HD grading');
insert into answer_values(questionnaire_id, answer_value) values(45, 'SABS Category II ADM');
insert into answer_values(questionnaire_id, answer_value) values(45, 'SABS Category II ADM Grading D3');
insert into answer_values(questionnaire_id, answer_value) values(45, 'SABS Category III grading');
insert into answer_values(questionnaire_id, answer_value) values(45, 'SABS Category IV grading');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '46', 'Please select the durtaion for your cover  ?'                     ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(46, 'Annually');
insert into answer_values(questionnaire_id, answer_value) values(46, 'Monthly');
insert into answer_values(questionnaire_id, answer_value) values(46, 'Once Off');
insert into answer_values(questionnaire_id, answer_value) values(46, 'Permanent');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '47', 'Please specify if secured by any other means :',                 4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '48', 'Please provide details of how it is secured :',                 1,    16,    'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '49', 'Are you currently insured ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '50', 'Please provide details of your previous insurance company ?'                     ,                    1,    18,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '51', 'Please provide details of losses of valuable goods of insured/uninsured the past 5 years ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '52', 'DATE :'                    ,                    1,    20,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '53', 'VALUE :'                     ,                    1,    20,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '54', 'TYPE OF LOSS :'                     ,                    1,    20,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '55', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    20,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '56', 'DATE :'                     ,                    1,    24,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '57', 'VALUE :'                     ,                    1,    24,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '58', 'TYPE OF LOSS :'                     ,                    1,    24,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '59', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    24,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '60', 'DATE :'                     ,                    1,    28,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '61', 'VALUE :'                     ,                    1,    28,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '62', 'TYPE OF LOSS :'                     ,                    1,    28,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '63', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    28,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '64', 'DATE :'                     ,                    1,    32,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '65', 'VALUE :'                     ,                    1,    32,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '66', 'TYPE OF LOSS :'                     ,                    1,    32,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('2', '67', 'Do you require SASRIA cover ?',                 4,  null,    null, 'false');


/*Product3*/
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '68', 'What do you wish to insure ?',                 3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash and Coins ');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash Coins and Valuables');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash Belonging to Standard Bank');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash Gold And Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash and Cameos Managed Units');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash and Gold Bullion');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash and Bullion');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Cash and Valuables');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Gold and Cash');
insert into answer_values(questionnaire_id, answer_value) values(68, 'Bullion');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '69', 'Please select the durtaion for your cover  ?'                     ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(69, 'Annually');
insert into answer_values(questionnaire_id, answer_value) values(69, 'Monthly');
insert into answer_values(questionnaire_id, answer_value) values(69, 'Once Off');
insert into answer_values(questionnaire_id, answer_value) values(69, 'Permanent');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '70', 'What is the maximum amount you wish to insure ?',                      2, 	null, 	null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '71', 'Is the above amount the total full value of the goods being moved ?',  4,	null, 	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '72', 'What is the total full value of the goods being moved ?',              2,   4, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '73', 'Do you want first loss cover for additional premium ?',               4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '74', 'Do you use the service of a professional valuables carriers ?',        4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '75', 'What is the name of the professional valuables carriers ?',            3,   7,	  	'true', 'true');
insert into answer_values(questionnaire_id, answer_value) values(75, 'Protea Coin Service');
insert into answer_values(questionnaire_id, answer_value) values(75, 'G4S Service');
insert into answer_values(questionnaire_id, answer_value) values(75, 'Fidelity Service');
insert into answer_values(questionnaire_id, answer_value) values(75, 'Imperial Logistics');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '76', 'Please specify by whom and how are the valuables carried :',                           1,	7, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '77', 'How many times per week are the valuables carried ?',                   3,  null,  	null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(77, '1 time /week');
insert into answer_values(questionnaire_id, answer_value) values(77, '2 times/week');
insert into answer_values(questionnaire_id, answer_value) values(77, '3 times/week');
insert into answer_values(questionnaire_id, answer_value) values(77, '4 times/week');
insert into answer_values(questionnaire_id, answer_value) values(77, '5 times/week');
insert into answer_values(questionnaire_id, answer_value) values(77, '6 times/week');
insert into answer_values(questionnaire_id, answer_value) values(77, '7 times/week');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '78', 'Please select from where and to where are the valuables carried:',                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(78, 'Port Elizabeth to Bloemfontein');
insert into answer_values(questionnaire_id, answer_value) values(78, 'Johannesburg to Durban');
insert into answer_values(questionnaire_id, answer_value) values(78, 'Polokwane to Mbombela');
insert into answer_values(questionnaire_id, answer_value) values(78, 'Rustenburg to Kimberley');
insert into answer_values(questionnaire_id, answer_value) values(78, 'Kimberley to Cape Town');
insert into answer_values(questionnaire_id, answer_value) values(78, 'Cape Town to Johannesburg ');
insert into answer_values(questionnaire_id, answer_value) values(78, 'Durban to Bloemfontein');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '79', 'What is the approximate distance ?'                 ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(79, '0km to 100km');
insert into answer_values(questionnaire_id, answer_value) values(79, '100km to 200km');
insert into answer_values(questionnaire_id, answer_value) values(79, '200km to 300km');
insert into answer_values(questionnaire_id, answer_value) values(79, '300km to 400km');
insert into answer_values(questionnaire_id, answer_value) values(79, '400km to 500km');
insert into answer_values(questionnaire_id, answer_value) values(79, '500km to 600km');
insert into answer_values(questionnaire_id, answer_value) values(79, '600km to 700km');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '80', 'Are you currently insured ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '81', 'Please provide details of your previous insurance company :'                     ,                    1,    13,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '82', 'Please provide details of losses of valuable goods of insured/uninsured the past 5 years ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '83', 'DATE :'                    ,                    1,    15,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '84', 'VALUE :'                     ,                    1,    15,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '85', 'TYPE OF LOSS :'                     ,                    1,    15,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '86', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    15,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '87', 'DATE :'                     ,                    1,    19,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '88', 'VALUE :'                     ,                    1,    19,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '89', 'TYPE OF LOSS :'                     ,                    1,    19,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '90', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    19,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '91', 'DATE :'                     ,                    1,    23,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '92', 'VALUE :'                     ,                    1,    23,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '93', 'TYPE OF LOSS :'                     ,                    1,    23,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '94', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    23,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '95', 'DATE :'                     ,                    1,    27,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '96', 'VALUE :'                     ,                    1,    27,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '97', 'TYPE OF LOSS :'                     ,                    1,    27,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('3', '98', 'Do you require SASRIA cover ?'                     ,                    4,    null,  null, 'false');


/*product4*/
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '99', 'What do you wish to insure ?',                 3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash and Coins ');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash Coins and Valuables');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash Belonging to Standard Bank');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash Gold And Diamonds');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash and Cameos Managed Units');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash and Gold Bullion');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash and Bullion');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Cash and Valuables');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Gold and Cash');
insert into answer_values(questionnaire_id, answer_value) values(99, 'Bullion');;
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '100', 'What is the maximum amount you wish to insure in Cash in transit ?',                      2, 	null, 	null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '101', 'Is the above amount the total full value of the goods being moved in  Cash in transit ?',  4,	null, 	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '102', 'What is the total full value of the goods being moved in Cash in transit ?',              2,   3, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '103', 'Do you want first loss cover for additional premium ?',               4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '104', 'Do you use the service of a professional valuables carriers ?',        4,   null,	null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '105', 'What is the name of the professional valuables carriers ?',            3,   6,	  	'true', 'true');
insert into answer_values(questionnaire_id, answer_value) values(105, 'Protea Coin Service');
insert into answer_values(questionnaire_id, answer_value) values(105, 'G4S Service');
insert into answer_values(questionnaire_id, answer_value) values(105, 'Fidelity Service');
insert into answer_values(questionnaire_id, answer_value) values(105, 'Imperial Logistics');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '106', 'Please specify by whom and how are the valuables carried :',                           1,	6, 		'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '107', 'Please select the durtaion for your cover  ?'                     ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(107, 'Annually');
insert into answer_values(questionnaire_id, answer_value) values(107, 'Monthly');
insert into answer_values(questionnaire_id, answer_value) values(107, 'Once Off');
insert into answer_values(questionnaire_id, answer_value) values(107, 'Permanent');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '108', 'How many times per week are the valuables carried ?',                   3,  null,  	null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(108, '1 time /week');
insert into answer_values(questionnaire_id, answer_value) values(108, '2 times/week');
insert into answer_values(questionnaire_id, answer_value) values(108, '3 times/week');
insert into answer_values(questionnaire_id, answer_value) values(108, '4 times/week');
insert into answer_values(questionnaire_id, answer_value) values(108, '5 times/week');
insert into answer_values(questionnaire_id, answer_value) values(108, '6 times/week');
insert into answer_values(questionnaire_id, answer_value) values(108, '7 times/week');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '109', 'Please select from where and to where are the valuables carried :',                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(109, 'Port Elizabeth to Bloemfontein');
insert into answer_values(questionnaire_id, answer_value) values(109, 'Johannesburg to Durban');
insert into answer_values(questionnaire_id, answer_value) values(109, 'Polokwane to Mbombela');
insert into answer_values(questionnaire_id, answer_value) values(109, 'Rustenburg to Kimberley');
insert into answer_values(questionnaire_id, answer_value) values(109, 'Kimberley to Cape Town');
insert into answer_values(questionnaire_id, answer_value) values(109, 'Cape Town to Johannesburg ');
insert into answer_values(questionnaire_id, answer_value) values(109, 'Durban to Bloemfontein');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '110', 'What is the approximate distance ?'                 ,                    3,    null,  null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(110, '0km to 100km');
insert into answer_values(questionnaire_id, answer_value) values(110, '100km to 200km');
insert into answer_values(questionnaire_id, answer_value) values(110, '200km to 300km');
insert into answer_values(questionnaire_id, answer_value) values(110, '300km to 400km');
insert into answer_values(questionnaire_id, answer_value) values(110, '400km to 500km');
insert into answer_values(questionnaire_id, answer_value) values(110, '500km to 600km');
insert into answer_values(questionnaire_id, answer_value) values(110, '600km to 700km');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '111', 'What is the maximum amount you wish to insure in Static ?', 				    2, 	null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '112', 'Is the above amount the total full value of the goods being stored in Static ?',  4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '113', 'What is the total full value of the goods being stored in Static ?',             2,  14,  'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '114', 'Please give a full description of the goods to be insured ?',          1,  null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '115', 'Please provide details of vault/safe ?',                                      4,  null,    null, 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '116', 'Please select the SABS safety category of the vault:',              3,  null,    null, 'true');
insert into answer_values(questionnaire_id, answer_value) values(116, 'No SABS grading');
insert into answer_values(questionnaire_id, answer_value) values(116, 'SABS Category I ');
insert into answer_values(questionnaire_id, answer_value) values(116, 'SABS Category II');
insert into answer_values(questionnaire_id, answer_value) values(116, 'SABS Category II HD grading');
insert into answer_values(questionnaire_id, answer_value) values(116, 'SABS Category II ADM');
insert into answer_values(questionnaire_id, answer_value) values(116, 'SABS Category II ADM Grading D3');
insert into answer_values(questionnaire_id, answer_value) values(116, 'SABS Category III grading');
insert into answer_values(questionnaire_id, answer_value) values(116, 'SABS Category IV grading');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '117', 'Are the goods going to be stored in vault ?',                                       4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '118', 'Is the vault secured with reinforced concrete on all sides as well as top and bottom ?',                 4,  19,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '119', 'Is vault fitted with interior seismic detectors inside the vault ?',                 4,  19,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '120', 'Is vault equipped with 24 hour infra-red cameras and normal CCTV 24 hours recording ?',                 4,  19,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '121', 'Does the vault have an alarm and is it linked to an external response company ?',                 4,  19,    'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '122', 'What is the type of storage of vault ?',                 1,  19,    'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '123', 'What is the address of the stored vault?',                 1,  19,    'false', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '124', 'Please specify if secured by any other means :',                 4,  null,    null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '125', 'Please provide details of how it is secured :',                 1,    26,    'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '126', 'Are you currently insured ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '127', 'Please provide details of your previous insurance company :'                     ,                    1,    28,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '128', 'Please provide details of losses of valuable goods of insured/uninsured the past 5 years ?'                     ,                    4,    null,  null, 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '129', 'DATE :'                     ,                    1,    30,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '130', 'VALUE :'                     ,                    1,    30,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '131', 'TYPE OF LOSS :'                     ,                    1,    30,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '132', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    30,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '133', 'DATE :'                     ,                    1,    34,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '134', 'VALUE :'                     ,                    1,    34,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '135', 'TYPE OF LOSS :'                     ,                    1,    34,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '136', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    34,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '137', 'DATE :'                     ,                    1,    38,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '138', 'VALUE :'                     ,                    1,    38,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '139', 'TYPE OF LOSS :'                     ,                    1,    38,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '140', 'Do you have more history details of insured/uninsured goods :'                     ,                    4,    38,  'true', 'false');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '141', 'DATE :'                     ,                    1,    42,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '142', 'VALUE :'                     ,                    1,    42,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '143', 'TYPE OF LOSS :'                     ,                    1,    42,  'true', 'true');
insert into questionnaires(product_id, sequence_number, question, answer_type_id, depends_on, on_answer, is_required)  values('4', '144', 'Do you require SASRIA cover ?',                 4,  null,    null, 'false');



