
/* Table login */
create table login (
    id integer generated by default as identity (start with 1, increment by 1) not null primary key,
    user_name varchar(32) not null, 
    password varchar(32) not null, 
    enabled boolean not null, 
    role varchar(16) not null
);

/* Table product */
create table products(
    id integer generated by default as identity (start with 1, increment by 1) not null primary key, 
    name varchar(50) not null, 
    description varchar(250),
    image varchar(150) 
);

/* Table answer_types */
create table answer_types(
    id integer generated by default as identity (start with 1, increment by 1) not null primary key,
    answer_type varchar(10) not null
);

/* Table questionnaires */
create table questionnaires(
    id integer generated by default as identity (start with 1, increment by 1) not null primary key, 
    product_id integer not null,
    sequence_number integer not null,
    question varchar(250) not null,
    answer_type_id integer not null,
    depends_on integer,
    if_answer varchar(128),
    constraint questionnaires_fk foreign key (product_id) references products (id),
    constraint questionnaires_fk_answers foreign key (answer_type_id) references answer_types (id)
);

/* Table questionnaires_options */
create table questionnaires_options(
    id integer generated by default as identity (start with 1, increment by 1) not null primary key,
    questionnaires_id integer not null,
    value varchar(150) not null,
    constraint questionnaires_fk_oprions foreign key (questionnaires_id) references questionnaires (id)

);
